// <auto-generated />
namespace CasusStartToBike.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Contextv21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Contextv21));
        
        string IMigrationMetadata.Id
        {
            get { return "202110251514203_Contextv2.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
